defaults: &defaults
  event:
    name: "Heart of Clojure Activities"
    start_time: 2019-08-01 00:00:00
    end_time: 2019-08-04 23:59:59
  host: "activities.heartofclojure.eu"
  mailers:
    from: "contact@heartofclojure.eu"
  errors:
    from: "contact@heartofclojure.eu"
    to:
      - "contact@heartofclojure.eu"
  seo:
    title: "Heart of Clojure Activities"
    author: "Heart of Clojure team"
    description: "List of events around Heart of Clojure"

development:
  <<: *defaults
  host: "activities.dev:3000"

test:
  <<: *defaults
  event:
    name: "Isle of Ruby"
    start_time: 2018-04-10T00:00:00+0100
    end_time: 2018-04-18T23:59:59+0100

staging:
  <<: *defaults
  host: "TBD"

production:
  <<: *defaults
